services:
  agent-zero:
    image: frdel/agent-zero-run:latest
    container_name: agent-zero
    ports:
      - "4001:80"
    # --- mounts ---
    volumes:
      # live source code (hot-reload)
      - "D:/Bear Projects/Agent Zero:/a0"            # MOUNT TO /a0 DIRECTLY
      # persistent runtime data (named volumes)
      - a0_data:/a0/tmp            # settings.json, memory, faiss, …
      - a0_logs:/a0/logs           # log files
      - a0_models:/root/.cache     # HF / Ollama downloads, etc.
volumes:
  a0_data:
  a0_logs:
  a0_models:
  ollama_models:
    external: true
    name: localai_ollama_storage


  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      TZ: "${TZ}"
    volumes:
      - ollama_models:/root/.ollama:rw
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
    profiles: ["gpu"]
    
networks:
  app-network:
    driver: bridge

