services:
  agent-zero:
    container_name: agent-zero
    build:
      context: ../..
      dockerfile: docker/run/Dockerfile
      args:
        BRANCH: development
    volumes:
      - ../..:/a0
    ports:
      - "4000:80"
      # - http://localhost:4000/
      # - http://127.0.0.1:4000/