services:
  agent-zero:
    container_name: agent-zero
    image: frdel/agent-zero-run:latest
    ports:
      - "4001:80"
    volumes:                        
      - "D:/Bear Projects/Agent Zero:/git/agent-zero"