services:
  agent-zero:
    container_name: agent-zero
    build:
      context: ../..
      dockerfile: docker/run/Dockerfile
      args:
        BRANCH: development
    volumes:
      - ../..:/a0
    ports:
      - "4000:80"
    networks:
      - app-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      TZ: "${TZ}"
    volumes:
      - ollama_models:/root/.ollama:rw
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
    profiles: ["gpu"]

volumes:
  ollama_models:
    external: true
    name: localai_ollama_storage

networks:
  app-network:
    driver: bridge
